name: MacOS

on:
  push:
    branches: [master]
    paths: ['.github/workflows/macos-arm64.yml']

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Pull repo
        uses: actions/checkout@v2

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: "3.24.0"

      - name: Compile process
        run: |
          mkdir build
          cd build
          cmake -G "Xcode" -DPROJECT_ARCH=arm64 ..
          cmake --build . -v

      - id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: v1.0.2-${{ steps.vars.outputs.sha_short }}-macosarm64
          path: |
            ./build/src/Debug/client-bevy
            ./libcef/Debug/Chromium Embedded Framework.framework
