name: Windows

on:
  push:
    branches: [test-ga]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup MSVC dev
        uses: ilammy/msvc-dev-cmd@v1

      - name: Compile and package
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" ..
          msbuild ./CEFHelperProcess.sln
          Compress-Archive -Path .\src\Debug\* -Destination build.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build/build.zip