name: Windows

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Pull repo
        uses: actions/checkout@v2
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup MSVC dev
        uses: ilammy/msvc-dev-cmd@v1

      - name: Compile process
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" ..
          msbuild ./CEFHelperProcess.sln

      - id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: v1.0.2-${{ steps.vars.outputs.sha_short }}-windowsx64
          path: ./build/src/Debug/
